# Generated by Django 3.1.4 on 2020-12-23 10:28

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('reference_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False, verbose_name='reference ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail address')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('address_1', models.CharField(blank=True, max_length=254)),
                ('address_2', models.CharField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=254)),
                ('newsletter', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
